name: Setup Chrome Remote Desktop on Windows

on:
  workflow_dispatch: # Cho phép chạy workflow thủ công từ giao diện GitHub

jobs:
  setup-chrome-rd:
    runs-on: windows-latest # Chạy trên máy ảo Windows mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Google Chrome
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile "chrome_setup.exe"
          Start-Process "chrome_setup.exe" -ArgumentList "/silent /install" -Wait

      - name: Install Chrome Remote Desktop Host
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chrome_remote_desktop_host.msi"
          Start-Process "msiexec.exe" -ArgumentList "/i", "chrome_remote_desktop_host.msi", "/quiet" -Wait
      
      - name: Configure Chrome Remote Desktop
        run: |
           & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AanRRrvNC4jCzaha9XDa7ZcLg5wW5FQnV4U1UhA0UP-nXscZCH4xjJ5wtNhedu-jrx2q3Q" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
           
      - name: Send PIN and Enter
        run: |
          Add-Type -AssemblyName System.Windows.Forms
          Start-Sleep -Seconds 10 # Chờ cửa sổ cấu hình Chrome Remote Desktop xuất hiện
          
          [System.Windows.Forms.SendKeys]::SendWait("111111")
          Start-Sleep -Seconds 1 # Chờ một chút trước khi nhấn Enter
          [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
